# Generated by Django 3.0.2 on 2020-02-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('birth_date', models.DateField(verbose_name='Data de  Nascimento')),
                ('age', models.DateField(verbose_name='Idade')),
                ('weight', models.CharField(max_length=10, verbose_name='Altura')),
                ('sex', models.CharField(max_length=30, verbose_name='Sexo')),
                ('color', models.CharField(max_length=30, verbose_name='Cor')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('cpf', models.CharField(max_length=20, verbose_name='CPF')),
                ('cns', models.CharField(max_length=40, verbose_name='Cartão SUS')),
                ('g_abo', models.CharField(max_length=20, verbose_name='G-ABO')),
                ('mother_name', models.CharField(max_length=155, verbose_name='Nome Mão')),
                ('death', models.DateTimeField()),
            ],
        ),
    ]
