# Generated by Django 3.0.2 on 2020-02-16 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_hospital_donor'),
        ('donor', '0002_auto_20200204_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='hospital',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital'),
        ),
    ]
