# Generated by Django 3.0.2 on 2020-02-16 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_donor_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='hospital',
        ),
    ]
