# Generated by Django 3.0.2 on 2020-02-27 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_donor_hospital'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='AgHBS_nr',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='AgHBS_r',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='AntiHBS_nr',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='AntiHBS_r',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='AntiHCV_nr',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='AntiHCV_r',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='AntiHIV_nr',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='AntiHIV_nr1_2',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='AntiHIV_r',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='AntiHIV_r1_2',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='AntiHTLV_nr',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='AntiHTLV_r',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='aveh',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='chagas_nr',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='chagas_r',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='coleta_liquor',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='dt_liquor',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='enc_anoxica',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='exm_img',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='exm_img_tipo',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='familia_inf',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='hsa',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='others',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='p_gastrometria',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='rb',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='resultado_liquor',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='sifilis_nr',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='sifilis_r',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='t_preenchido',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='tce',
        ),
        migrations.AddField(
            model_name='registration',
            name='cause_ME',
            field=models.TextField(default=1, verbose_name='Causa do ME'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='donor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donor.Donor'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='dt_cultura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='dt_rs2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='dt_rs3',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='inicio1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='inicio2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='inicio3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='ureia',
            field=models.TextField(verbose_name='uréia'),
        ),
    ]
