# Generated by Django 3.0.2 on 2020-03-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200309_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='creatinina',
            field=models.CharField(max_length=10, verbose_name='Creatinina'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='ureia',
            field=models.CharField(max_length=10, verbose_name='uréia'),
        ),
    ]
