# Generated by Django 3.0.2 on 2020-02-04 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Hospital Notificante')),
                ('bed', models.CharField(max_length=20, verbose_name='Leito')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('branch', models.CharField(max_length=10, verbose_name='Ramal')),
                ('donor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donor.Donor')),
            ],
        ),
    ]
